version: "3"
services:
  freshrss:
    image: freshrss/freshrss
    container_name: 'freshrss'
    restart: unless-stopped
    networks:
      - webapp
    volumes:
      - "$STACK_DATA/data:/var/www/FreshRSS/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.freshRss.loadbalancer.server.port=80"
      - "traefik.http.routers.freshRss.rule=Host(`rss.${DOMAIN}`)"
      - "traefik.http.routers.freshRss.entrypoints=websecure"
      - "traefik.http.routers.freshRss.tls.certresolver=leresolver"
      - "traefik.http.middlewares.freshRssHeaders.headers.contentSecurityPolicy=default-src 'self' data:; 'unsafe-inline'"
      - "traefik.http.middlewares.freshRssHeaders.headers.framedeny=true"
      - "traefik.http.middlewares.freshRssHeaders.headers.sslredirect=true"
      - "traefik.http.middlewares.freshRssHeaders.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.freshRssHeaders.headers.stsPreload=true"
      - "traefik.http.middlewares.freshRssHeaders.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.freshRssHeaders.headers.contentTypeNosniff=true"
      - "traefik.http.middlewares.freshRssHeaders.headers.browserXssFilter=true"
      - "traefik.http.middlewares.freshRssHeaders.headers.stsSeconds=31536000"
      - "traefik.http.routers.freshRss.middlewares=freshRssHeaders"
    environment:
      - "TZ=$TIME_ZONE"
      - "CRON_MIN=4,34"
networks:
  webapp:
    external:
      name: 'webapp'